<?php

/**
 * Member
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Member extends BaseMember
{
    public function setUp()
    {
        parent::setUp();
        
        $this->hasMutator('password', '_encrypt_password');
    }

    protected function _encrypt_password($value) 
    {
        $this->_set('password', md5($value));
    }
}