<?php

/**
 * PdoMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PdoMember extends BaseMember implements DeepCI_Validation_PdoInterface 
{
	/**
	 * require, number, email, url, date	-- array('xxx','error message');
	 */
	public function validation()
	{
		$rules = array();
		
		// username
		$rules['username'][]	= array('required');
		
		// passowrd
		$rules['passowrd'][]	= array('required');
		$rules['passowrd'][]	= array('number');
		
		// email
		$rules['email'][]	= array('required');
		$rules['email'][]	= array('email');
		
		// create_date
		$rules['create_date'][]	= array('required');
		$rules['create_date'][]	= array('date');
		
		return $rules;
	}
}